name: workers_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.3.3 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8
  mobx: ^2.2.1
  flutter_mobx: ^2.2.0
  dart_json_mapper: ^2.2.7
  get_it: ^7.6.7
  shared_preferences: ^2.2.2
  image_picker: ^1.0.7
  firebase_core: ^2.24.2
  provider: ^6.1.5
  url_launcher: ^6.3.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.1
  mobx_codegen: ^2.6.0
  build_runner: ^2.4.7

flutter:
  uses-material-design: true

  assets:
    - lib/Helpers/Resources/Images/
